function S = local_prepare_one_bodypart_map( ...
    result, basis, trial_info, body_part, is_average_mode, varargin)

p = inputParser;
p.addParameter('UseOccupancyMask', true, @(x) islogical(x) && isscalar(x));
p.addParameter('MaskSmoothSigma', 1, @(x) isnumeric(x) && isscalar(x) && x >= 0);
p.addParameter('MaskQuantileNonzero', 0.2, @(x) isnumeric(x) && isscalar(x) && x >= 0 && x <= 1);
p.addParameter('MaskUseSmoothedOcc', true, @(x) islogical(x) && isscalar(x));
p.addParameter('UseMaskedRegionForCLim', true, @(x) islogical(x) && isscalar(x));
p.addParameter('PositionMode', 'basis', @(x) any(strcmpi(string(x), ["basis","bin"])));

p.parse(varargin{:});
position_mode = lower(string(p.Results.PositionMode));

switch position_mode
    case "basis"
        S = Kin.local_prepare_one_bodypart_field( ...
            result, basis, trial_info, body_part, is_average_mode, ...
            'UseOccupancyMask', p.Results.UseOccupancyMask, ...
            'MaskSmoothSigma', p.Results.MaskSmoothSigma, ...
            'MaskQuantileNonzero', p.Results.MaskQuantileNonzero, ...
            'MaskUseSmoothedOcc', p.Results.MaskUseSmoothedOcc, ...
            'UseMaskedRegionForCLim', p.Results.UseMaskedRegionForCLim);

    case "bin"
        S = Kin.local_prepare_one_bodypart_binmap( ...
            result, basis, trial_info, body_part, ...
            'UseOccupancyMask', p.Results.UseOccupancyMask, ...
            'MaskSmoothSigma', p.Results.MaskSmoothSigma, ...
            'MaskQuantileNonzero', p.Results.MaskQuantileNonzero, ...
            'MaskUseSmoothedOcc', p.Results.MaskUseSmoothedOcc, ...
            'UseMaskedRegionForCLim', p.Results.UseMaskedRegionForCLim);

    otherwise
        error('Unknown position_mode: %s', position_mode);
end
end